# Generated by Django 6.0.3 on 2026-04-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('upc', models.CharField(max_length=14, unique=True)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('dairy', 'Dairy'), ('frozen', 'Frozen'), ('pantry', 'Pantry')], default='pantry', max_length=20)),
            ],
        ),
    ]
