# Generated by Django 6.0.3 on 2026-04-14 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedProduct',
            fields=[
                ('upc', models.CharField(help_text='Universal Product Code as returned by Kroger API.', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('categories', models.CharField(blank=True, default='', help_text='Comma-separated Kroger categories e.g. "Dairy". Used in Gemini vegan prompt.', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image_front', models.URLField(blank=True, default='')),
                ('image_back', models.URLField(blank=True, default='', help_text='Back-of-pack image. Passed to Gemini Vision for vegan verification.')),
                ('image_left', models.URLField(blank=True, default='')),
                ('image_right', models.URLField(blank=True, default='')),
                ('is_vegan', models.BooleanField(default=None, null=True)),
                ('vegan_checked', models.BooleanField(default=False, help_text='True once Gemini has been called, regardless of result.')),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cached product',
                'verbose_name_plural': 'cached products',
            },
        ),
        migrations.CreateModel(
            name='CachedStore',
            fields=[
                ('location_id', models.CharField(help_text='Kroger locationId, e.g. "01400376".', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Store banner name, e.g. "Kroger".', max_length=100)),
                ('store_number', models.CharField(blank=True, default='', help_text='Store number, e.g. "632". Combined with name for display.', max_length=10)),
                ('address_line', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Miles from the zip that last fetched this store. Approximate.', max_digits=6, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cached store',
                'verbose_name_plural': 'cached stores',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_per_unit', models.CharField(blank=True, default='', help_text='e.g. "$0.08 / oz" as returned by Kroger.', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('sold_by', models.CharField(blank=True, default='', help_text='e.g. "UNIT" or "WEIGHT" from Kroger items[].soldBy.', max_length=20)),
                ('size', models.CharField(blank=True, default='', help_text='e.g. "1 gal" from Kroger items[].size.', max_length=50)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='kroger_app.cachedproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='kroger_app.cachedstore')),
            ],
            options={
                'verbose_name': 'product price',
                'verbose_name_plural': 'product prices',
                'indexes': [models.Index(fields=['store'], name='kroger_app__store_i_a75307_idx'), models.Index(fields=['product', 'store'], name='kroger_app__product_5447fd_idx')],
                'unique_together': {('product', 'store')},
            },
        ),
    ]
