# Generated by Django 6.0.3 on 2026-04-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedstore',
            name='searched_zip',
            field=models.CharField(blank=True, default='', help_text='The zip code that was queried when this store was cached.', max_length=10),
        ),
    ]
