# Generated by Django 6.0.3 on 2026-04-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroger_app', '0003_cachedstore_info_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedstore',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cachedstore',
            name='longitude',
        ),
    ]
