# Generated by Django 6.0.3 on 2026-04-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_remove_appuser_username_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
