# Generated by Django 6.0.3 on 2026-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_appuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_uses',
            field=models.PositiveIntegerField(default=0, help_text='Number of fresh Gemini vegan checks this user has made.'),
        ),
    ]
