# Generated by Django 6.0.3 on 2026-04-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(help_text='Soft ref to CachedProduct.upc — plain CharField, not FK.', max_length=20)),
                ('product_name', models.CharField(help_text='Denormalized for display without a CachedProduct lookup.', max_length=255)),
                ('preferred_store_id', models.CharField(blank=True, default='', help_text='location_id of the store the user added this item from.', max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('checked', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list_app.shoppinglist')),
            ],
            options={
                'verbose_name': 'shopping list item',
                'verbose_name_plural': 'shopping list items',
                'ordering': ['checked', '-added_at'],
            },
        ),
    ]
