# Generated by Django 6.0.3 on 2026-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_shoppinglist_updated_at_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['checked'], 'verbose_name': 'shopping list item', 'verbose_name_plural': 'shopping list items'},
        ),
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='preferred_store_id',
            new_name='product_store_id',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='notes',
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='upc',
            field=models.CharField(blank=True, default='', help_text='Soft reference to CachedProduct.upc for convenience.', max_length=20),
        ),
    ]
