# Generated by Django 6.0.3 on 2026-04-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0003_alter_shoppinglistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'verbose_name': 'shopping list item', 'verbose_name_plural': 'shopping list items'},
        ),
    ]
