# Generated by Django 6.0.3 on 2026-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0004_alter_shoppinglistitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='store_address',
            field=models.CharField(blank=True, default='', help_text='Denormalized store address line.', max_length=255),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='store_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized store display name so the list is readable without a Kroger API call.', max_length=255),
        ),
    ]
